// Lake data API — the single read-side interface over the registry + live readings.
// Generated by scripts/fetch-levels.mjs (run locally + weekly in CI). Never edit by hand;
// add a lake to src/data/lakes.seed.json and re-run the pipeline.

import lakes from '../data/lakes.json';
import levels from '../data/levels.json';

export interface LakeEntry {
  slug: string;
  name: string;
  state: string;
  river: string;
  operator: string;
  full_pool_ft: number | null;
  capacity_af: number | null;
  vol: number | null;
  kd: number | null;
  feed: string | null;
  usgs_site: string | null;
  cdec_id: string | null;
}

export interface Reading {
  level_ft: number | null;
  storage_af: number | null;
  pct_full: number | null;
  feet_from_full: number | null;
  param: string;
  delta_24h: number | null;
  series: { t: string; v: number; storage?: boolean }[];
  as_of: string;
  feed: string;
  fresh: boolean;
}

export const LAKES = lakes as LakeEntry[];
const LEVELS = levels as Record<string, Reading>;

export function getLake(slug: string): LakeEntry | undefined {
  return LAKES.find((l) => l.slug === slug);
}

// Canonical feed-label normalizer. levels.json stores feed lowercase ('usgs' /
// 'cdec' / 'usbr'); the prior exact-match on uppercase 'CDEC' mislabeled every
// CDEC and USBR lake as 'USGS' in the QAS, FAQ, JSON-LD source chain, and
// operator-page link. Single source of truth — call this everywhere a feed
// identity is rendered or branched on. Returns null for unknown/missing feeds.
export function feedLabel(feed?: string | null): 'CDEC' | 'USBR' | 'USGS' | null {
  if (!feed) return null;
  const f = feed.toLowerCase();
  if (f === 'cdec') return 'CDEC';
  if (f === 'usbr') return 'USBR';
  if (f === 'usgs') return 'USGS';
  return null;
}

export function getReading(slug: string): Reading | undefined {
  return LEVELS[slug];
}

export function hasLive(slug: string): boolean {
  const r = LEVELS[slug];
  return !!(r && r.fresh);
}

// Lakes with a verified-current reading — the live "now" set shown on the homepage.
export function freshLakes(): { lake: LakeEntry; reading: Reading }[] {
  return LAKES.map((lake) => ({ lake, reading: LEVELS[lake.slug] }))
    .filter((x) => x.reading && x.reading.fresh) as { lake: LakeEntry; reading: Reading }[];
}

// Group all registry lakes by state (for the directory / state pages).
export function byState(): Record<string, LakeEntry[]> {
  const m: Record<string, LakeEntry[]> = {};
  for (const l of LAKES) (m[l.state] ||= []).push(l);
  return m;
}

// Status bucket + tone. Works for BOTH percent-full lakes (CDEC/USBR with
// storage) and elevation-only lakes (USGS reservoir elevations that have no
// storage → no pct_full). For the latter we derive a bucket from feet_from_full
// so a lake with a live elevation is never mislabeled "no live reading".
// Never color alone (design principle: color-blind safe) — every tone has a label.
export function status(pct: number | null, feetFromFull: number | null = null): { label: string; tone: 'green' | 'cyan' | 'amber' | 'red' } {
  if (pct != null) {
    if (pct >= 90) return { label: 'near full', tone: 'green' };
    if (pct >= 70) return { label: 'healthy', tone: 'cyan' };
    if (pct >= 45) return { label: 'below normal', tone: 'amber' };
    return { label: 'low', tone: 'red' };
  }
  // No %full: infer from how far below full-pool the elevation sits.
  if (feetFromFull != null) {
    if (feetFromFull <= 3) return { label: 'near full', tone: 'green' };
    if (feetFromFull <= 10) return { label: 'healthy', tone: 'cyan' };
    if (feetFromFull <= 25) return { label: 'below normal', tone: 'amber' };
    return { label: 'low', tone: 'red' };
  }
  return { label: 'no live reading', tone: 'amber' };
}

// "Can I launch?" interpretation from the level (the value-add the raw tables never give).
// Heuristic against percent-full where available; else against feet-from-full.
export function launchRead(r: Reading | undefined): { ok: boolean; text: string } {
  if (!r || !r.fresh) return { ok: false, text: 'Live level feed connecting. Check the operator page before you go.' };
  if (r.pct_full != null) {
    if (r.pct_full >= 60) return { ok: true, text: 'Lake is well within its normal pool; most boat ramps are usable. Confirm your specific ramp, which can close independently of lake level.' };
    if (r.pct_full >= 35) return { ok: true, text: 'Lake is lower than normal; some ramps may be out of the water. Check ramp status before launching.' };
    return { ok: false, text: 'Lake is well below normal pool. Expect closed ramps and exposed hazards. Launching is risky; verify conditions.' };
  }
  if (r.feet_from_full != null) {
    if (r.feet_from_full <= 3) return { ok: true, text: 'Lake is near full pool; most ramps should be open. Confirm your specific ramp before you go.' };
    if (r.feet_from_full <= 12) return { ok: true, text: 'Lake is a few feet below full; some ramps may be out. Check ramp status before launching.' };
    return { ok: false, text: 'Lake is well below full pool. Expect closed ramps and exposed hazards. Verify conditions before launching.' };
  }
  return { ok: false, text: 'Level data present but ramp condition can’t be inferred. Check the operator’s ramp status page.' };
}

// Stable HTML-escaped lake name for <title>/head.
export function fmtNum(n: number | null | undefined, d = 1): string {
  if (n == null || Number.isNaN(n)) return '—';
  return n.toLocaleString('en-US', { minimumFractionDigits: d, maximumFractionDigits: d });
}

export function stateName(code: string): string {
  return (STATE_NAMES as Record<string, string>)[code] || code;
}

const STATE_NAMES: Record<string, string> = {
  CA: 'California', TX: 'Texas', NV: 'Nevada', UT: 'Utah', GA: 'Georgia',
  OK: 'Oklahoma', MO: 'Missouri', VA: 'Virginia', NC: 'North Carolina',
  KY: 'Kentucky', AL: 'Alabama', AZ: 'Arizona', CO: 'Colorado', FL: 'Florida',
};

// Lake Powell operating-band reference elevations — PUBLISHED constants (not live
// measurements), so they live in code. USBR Glen Canyon Dam publishes full pool,
// minimum power pool, and dead pool; capacity and length are the NPS Glen Canyon NRA
// FAQ figures. The all-time recorded low (3,519.92 ft on 2023-04-13) is corroborated
// by NASA Earth Observatory ("just below 3,520 feet") and the American Southwest
// record cited via Glen Canyon NRA; it replaced an earlier 3,519.28 ft figure that no
// fetchable primary source substantiated (validated 2026-06-29). Exposed so the
// Powell page never types a reference number by hand. Other lakes render the band
// only if/when wired here.
export const POWELL_BAND = {
  fullPoolFt: 3700,
  minPowerPoolFt: 3490,
  deadPoolFt: 3370,
  recordLowFt: 3519.92,
  fullCapacityMaf: 27,
  lengthMi: 186,
  // NPS Glen Canyon FAQ: "Its maximum depth (at Glen Canyon Dam) is 561 feet (171 m)".
  // Streambed at the dam = fullPoolFt - maxDepthFullPoolFt = 3139 ft; current depth at
  // the dam = live elevation - 3139. Verified against the live NPS page 2026-07-16.
  maxDepthFullPoolFt: 561,
};

// The three federal figures for Lake Powell on 2023-04-13. They differ because a daily
// pool elevation, an approved daily mean and a 15-minute instantaneous reading are three
// different measurements of the same lake, not because any of them is wrong. All three
// were re-fetched and citation-verified in the portfolio-seo-pipeline run 2026-08-14.
// NOTE ON WORDING: no fetchable source states in words that 2023-04-13 was the minimum
// DAY of the record, so nothing here may be called a record low. USGS EROS states only
// that the lowest level came in April 2023. Describe these as the figures each series
// publishes for that date, which is exactly what they are.
export const POWELL_APRIL_2023 = {
  riseFt: 3519.92,
  riseUrl: 'https://www.usbr.gov/uc/water/hydrodata/reservoir_data/919/csv/49.csv',
  usgsDailyMeanFt: 3519.5,
  usgsDailyMeanUrl: 'https://waterservices.usgs.gov/nwis/dv/?sites=09379900&parameterCd=62614&startDT=2023-04-10&endDT=2023-04-16&format=rdb',
  usgsInstantMinFt: 3519.1,
  usgsInstantMinUrl: 'https://nwis.waterservices.usgs.gov/nwis/iv/?sites=09379900&parameterCd=62614&startDT=2023-04-13&endDT=2023-04-13&format=rdb',
  erosUrl: 'https://eros.usgs.gov/earthshots/water-levels',
};

// Lake Powell launch ramps. The roster, the minimum elevations and the per vessel class
// availability all come from the NPS "Lake Level Effects to Launch Ramps and Services"
// table, refetched on every build by scripts/fetch-powell-ramps.mjs. Availability is
// operational and changes as the lake drops, so it is never carried as a constant here.
import rampData from '../data/powell-ramps.json';

export type PowellRamp = {
  name: string;
  minFt: number;
  houseboats: string | null;
  smallMotorized: string | null;
  nonMotorized: string | null;
  note: string;
};

export function powellRamps(): PowellRamp[] {
  const rows = (rampData as any)?.ramps;
  return Array.isArray(rows) ? (rows as PowellRamp[]) : [];
}
export function powellRampsAsOf(): string | null {
  return (rampData as any)?.as_of ?? null;
}
export const POWELL_RAMPS_SOURCE: string = (rampData as any)?.source ?? 'https://www.nps.gov/glca/learn/changing-lake-levels.htm';

// The Park Service also publishes a page per ramp, and for two ramps that page states a
// DIFFERENT minimum elevation than the summary table above. Both figures are quoted
// verbatim from the live NPS pages, re-fetched and citation-verified through the
// portfolio-seo-pipeline run 2026-08-14. This disagreement is the reason the page shows
// the ramp page figure beside the table figure instead of silently picking one.
export const POWELL_RAMP_PAGES = [
  {
    // Table says 3545 ft, the ramp's own page says above 3548 ft.
    table: 'Wahweap Main Launch Ramp',
    pageMinFt: 3548,
    url: 'https://www.nps.gov/places/wahweap-main-launch-ramp.htm',
    quote: 'This launch ramp is available to motorized vessels when the lake level elevation is above 3548 ft.',
  },
  {
    // Table says 3549 ft, the ramp's own page says below 3540 ft for vessels under 25 ft.
    table: 'Bullfrog Main Launch Ramp Spur',
    pageMinFt: 3540,
    url: 'https://www.nps.gov/places/bullfrog-main-launch-ramp.htm',
    quote: "available for vessels less than 25' long until the lake is below 3540'",
  },
  {
    table: 'Wahweap Stateline Auxiliary Launch Ramp',
    pageMinFt: 3515,
    url: 'https://www.nps.gov/places/stateline-auxiliary-launch-ramp.htm',
    quote: 'This launch ramp is operable for vessel launch and retrieve at lake elevation 3515 ft or above.',
  },
  {
    table: 'Halls Crossing Launch Ramp',
    pageMinFt: 3557,
    url: 'https://www.nps.gov/places/halls-crossing-launch-ramp.htm',
    quote: 'This ramp is available for all vessel launching until the lake level elevation 3557 ft or above.',
  },
  {
    table: 'Bullfrog Main Launch Ramp',
    pageMinFt: 3578,
    url: 'https://www.nps.gov/places/bullfrog-main-launch-ramp.htm',
    quote: "The ramp is operable for launching motorized vessels until the lake level is below 3578'.",
  },
];

// Net change across a reading's series (last minus first). The series spans ~30 days
// (SERIES_DAYS in fetch-levels.mjs), so this is the ~30-day elevation change. Pure
// math on the validated USGS reading; returns null if the series is too short.
export function changeOverSeries(series: { t: string; v: number }[] | undefined): number | null {
  if (!series || series.length < 2) return null;
  const last = series[series.length - 1].v;
  const first = series[0].v;
  if (!Number.isFinite(last) || !Number.isFinite(first)) return null;
  return Math.round((last - first) * 100) / 100;
}

// Linear share of the live-storage elevation band sitting below full pool. Honest
// geometric quantity (elevation distance), NOT a storage-volume claim — reservoirs
// are wider near the top so volume is not linear in elevation. Returns null unless
// both full pool and a lower band marker exist for the lake.
export function liveBandBelowFullPct(levelFt: number | null, fullPoolFt: number | null, lowerBandFt: number | null): number | null {
  if (levelFt == null || fullPoolFt == null || lowerBandFt == null) return null;
  const band = fullPoolFt - lowerBandFt;
  if (band <= 0) return null;
  return Math.round(((fullPoolFt - levelFt) / band) * 100 * 100) / 100;
}


// ---------------------------------------------------------------------------
// Lake Powell, the COMPLETE Reclamation daily record (site 919), refreshed by
// scripts/fetch-powell-history.mjs on every build.
//
// This replaces POWELL_BAND.recordLowFt as the source of any record claim. That
// constant was hand-typed as 3519.92 and labelled "Record low since first fill".
// On 2026-08-20 the lake fell below it, so the band card rendered "-1.0 ft above"
// — a negative number inside a hardcoded direction word — beside a label that had
// stopped being true. A constant cannot track a record; a computation over the
// whole file can, and that is what these figures are.
//
// It also resolves the sourcing objection recorded above POWELL_APRIL_2023: no
// agency states in words which single DAY of the record was lowest, so the ranking
// may not be asserted from a press release or a query window. Reclamation's own
// complete daily file settles it by measurement over the entire population.
import powellHistory from '../data/powell-history.json';

export type PowellHistoryStats = {
  latestDate: string; latestFt: number; totalDays: number;
  recordStart: string; recordEnd: string;
  recordHighFt: number; recordHighDate: string;
  seriesLowFt: number; seriesLowDate: string;
  postFillLowFt: number; postFillLowDate: string;
  firstFillCutoff: string; latestIsPostFillLow: boolean;
  daysBelowLatest: number; firstBelowDate: string | null; lastBelowDate: string | null;
  allLowerDaysArePreFill: boolean;
  medianForDateFt: number; rankForDate: number; yearsForDate: number;
  lowestSameDateFt: number; lowestSameDateDate: string;
  vsMedianForDateFt: number;
  completeYears: number;
  peakMonth: string; peakMonthCount: number;
  troughMonth: string; troughMonthCount: number;
  runnerUpTroughMonth: string | null; runnerUpTroughCount: number | null;
  peakMonthShare: number | null; troughMonthShare: number | null;
  peakTop3: { month: string; count: number }[];
  troughTop3: { month: string; count: number }[];
  seasonalIsPronounced: boolean;
};

export const POWELL_HISTORY = (powellHistory as any).stats as PowellHistoryStats;

// Lake Mead carries the same shape from the same kind of file (Reclamation site 921, daily from
// 1935-02-02). Its band constants come from Reclamation's published Hoover Dam figures.
import meadHistory from '../data/mead-history.json';
export const MEAD_HISTORY = (meadHistory as any).stats as PowellHistoryStats;
export const MEAD_HISTORY_MONTHLY = ((meadHistory as any).monthly ?? []) as [string, number][];
export const MEAD_HISTORY_DAILY = String((meadHistory as any).daily ?? '');
export const MEAD_HISTORY_DAILY_START = String((meadHistory as any).dailyStart ?? '');
export const MEAD_HISTORY_SOURCE: string =
  (meadHistory as any)?.source ?? 'https://www.usbr.gov/uc/water/hydrodata/reservoir_data/921/csv/49.csv';
export const MEAD_HISTORY_CATALOG: string =
  (meadHistory as any)?.catalog ?? 'https://data.usbr.gov/catalog/2362/item/508';

// Hoover Dam operating landmarks, all Reclamation-published. Full pool is the elevation at the
// top of the raised spillway gates; minimum power pool is where the plant can no longer generate;
// dead pool is the lowest elevation from which water can pass the dam at all.
export const MEAD_BAND = {
  fullPoolFt: 1229,
  minPowerPoolFt: 950,
  deadPoolFt: 895,
};
export const POWELL_HISTORY_MONTHLY = ((powellHistory as any).monthly ?? []) as [string, number][];
// The complete daily series, delta-encoded (see scripts/fetch-powell-history.mjs). Shipped to the
// browser so the lookup answers from the same numbers the chart draws, with no network call.
export const POWELL_HISTORY_DAILY = String((powellHistory as any).daily ?? '');
export const POWELL_HISTORY_DAILY_START = String((powellHistory as any).dailyStart ?? '');
export const POWELL_HISTORY_SOURCE: string =
  (powellHistory as any)?.source ?? 'https://www.usbr.gov/uc/water/hydrodata/reservoir_data/919/csv/49.csv';
export const POWELL_HISTORY_CATALOG: string =
  (powellHistory as any)?.catalog ?? 'https://data.usbr.gov/catalog/2362/item/508';

// Compare a reading to a fixed mark and return the MAGNITUDE plus the direction word,
// so no template ever prints a signed number into a hardcoded "above". A reading equal
// to the mark at the precision shown reports "level with", never "0.0 ft above".
export function compareToMark(
  levelFt: number | null | undefined,
  markFt: number | null | undefined,
  decimals = 1,
): { ft: number; dir: 'above' | 'below' | 'level with'; text: string } | null {
  if (levelFt == null || markFt == null || !Number.isFinite(levelFt) || !Number.isFinite(markFt)) return null;
  const raw = levelFt - markFt;
  const f = 10 ** decimals;
  const rounded = Math.round(raw * f) / f;
  const ft = Math.abs(rounded);
  const dir = rounded > 0 ? 'above' : rounded < 0 ? 'below' : 'level with';
  const text = dir === 'level with'
    ? `level with it at this precision`
    : `${ft.toFixed(decimals)} ft ${dir}`;
  return { ft, dir, text };
}

// Human date for a YYYY-MM-DD string, used beside every history figure.
export function fmtRecordDate(iso: string | null | undefined): string {
  if (!iso || !/^\d{4}-\d{2}-\d{2}$/.test(iso)) return '';
  const [y, m, d] = iso.split('-').map(Number);
  const months = ['January','February','March','April','May','June','July','August','September','October','November','December'];
  return `${months[m - 1]} ${d}, ${y}`;
}
