// Lake data API — the single read-side interface over the registry + live readings.
// Generated by scripts/fetch-levels.mjs (run locally + weekly in CI). Never edit by hand;
// add a lake to src/data/lakes.seed.json and re-run the pipeline.

import lakes from '../data/lakes.json';
import levels from '../data/levels.json';

export interface LakeEntry {
  slug: string;
  name: string;
  state: string;
  river: string;
  operator: string;
  full_pool_ft: number | null;
  capacity_af: number | null;
  vol: number | null;
  kd: number | null;
  feed: string | null;
  usgs_site: string | null;
  cdec_id: string | null;
}

export interface Reading {
  level_ft: number | null;
  storage_af: number | null;
  pct_full: number | null;
  feet_from_full: number | null;
  param: string;
  delta_24h: number | null;
  series: { t: string; v: number; storage?: boolean }[];
  as_of: string;
  feed: string;
  fresh: boolean;
}

export const LAKES = lakes as LakeEntry[];
const LEVELS = levels as Record<string, Reading>;

export function getLake(slug: string): LakeEntry | undefined {
  return LAKES.find((l) => l.slug === slug);
}

export function getReading(slug: string): Reading | undefined {
  return LEVELS[slug];
}

export function hasLive(slug: string): boolean {
  const r = LEVELS[slug];
  return !!(r && r.fresh);
}

// Lakes with a verified-current reading — the live "now" set shown on the homepage.
export function freshLakes(): { lake: LakeEntry; reading: Reading }[] {
  return LAKES.map((lake) => ({ lake, reading: LEVELS[lake.slug] }))
    .filter((x) => x.reading && x.reading.fresh) as { lake: LakeEntry; reading: Reading }[];
}

// Group all registry lakes by state (for the directory / state pages).
export function byState(): Record<string, LakeEntry[]> {
  const m: Record<string, LakeEntry[]> = {};
  for (const l of LAKES) (m[l.state] ||= []).push(l);
  return m;
}

// Status bucket + tone. Works for BOTH percent-full lakes (CDEC/USBR with
// storage) and elevation-only lakes (USGS reservoir elevations that have no
// storage → no pct_full). For the latter we derive a bucket from feet_from_full
// so a lake with a live elevation is never mislabeled "no live reading".
// Never color alone (design principle: color-blind safe) — every tone has a label.
export function status(pct: number | null, feetFromFull: number | null = null): { label: string; tone: 'green' | 'cyan' | 'amber' | 'red' } {
  if (pct != null) {
    if (pct >= 90) return { label: 'near full', tone: 'green' };
    if (pct >= 70) return { label: 'healthy', tone: 'cyan' };
    if (pct >= 45) return { label: 'below normal', tone: 'amber' };
    return { label: 'low', tone: 'red' };
  }
  // No %full: infer from how far below full-pool the elevation sits.
  if (feetFromFull != null) {
    if (feetFromFull <= 3) return { label: 'near full', tone: 'green' };
    if (feetFromFull <= 10) return { label: 'healthy', tone: 'cyan' };
    if (feetFromFull <= 25) return { label: 'below normal', tone: 'amber' };
    return { label: 'low', tone: 'red' };
  }
  return { label: 'no live reading', tone: 'amber' };
}

// "Can I launch?" interpretation from the level (the value-add the raw tables never give).
// Heuristic against percent-full where available; else against feet-from-full.
export function launchRead(r: Reading | undefined): { ok: boolean; text: string } {
  if (!r || !r.fresh) return { ok: false, text: 'Live level feed connecting. Check the operator page before you go.' };
  if (r.pct_full != null) {
    if (r.pct_full >= 60) return { ok: true, text: 'Lake is well within its normal pool; most boat ramps are usable. Confirm your specific ramp, which can close independently of lake level.' };
    if (r.pct_full >= 35) return { ok: true, text: 'Lake is lower than normal; some ramps may be out of the water. Check ramp status before launching.' };
    return { ok: false, text: 'Lake is well below normal pool. Expect closed ramps and exposed hazards. Launching is risky; verify conditions.' };
  }
  if (r.feet_from_full != null) {
    if (r.feet_from_full <= 3) return { ok: true, text: 'Lake is near full pool; most ramps should be open. Confirm your specific ramp before you go.' };
    if (r.feet_from_full <= 12) return { ok: true, text: 'Lake is a few feet below full; some ramps may be out. Check ramp status before launching.' };
    return { ok: false, text: 'Lake is well below full pool. Expect closed ramps and exposed hazards. Verify conditions before launching.' };
  }
  return { ok: false, text: 'Level data present but ramp condition can’t be inferred. Check the operator’s ramp status page.' };
}

// Stable HTML-escaped lake name for <title>/head.
export function fmtNum(n: number | null | undefined, d = 1): string {
  if (n == null || Number.isNaN(n)) return '—';
  return n.toLocaleString('en-US', { minimumFractionDigits: d, maximumFractionDigits: d });
}

export function stateName(code: string): string {
  return (STATE_NAMES as Record<string, string>)[code] || code;
}

const STATE_NAMES: Record<string, string> = {
  CA: 'California', TX: 'Texas', NV: 'Nevada', UT: 'Utah', GA: 'Georgia',
  OK: 'Oklahoma', MO: 'Missouri', VA: 'Virginia', NC: 'North Carolina',
  KY: 'Kentucky', AL: 'Alabama', AZ: 'Arizona', CO: 'Colorado', FL: 'Florida',
};

// Lake Powell operating-band reference elevations — PUBLISHED constants (not live
// measurements), so they live in code. USBR Glen Canyon Dam publishes full pool,
// minimum power pool, and dead pool; capacity and length are the NPS Glen Canyon NRA
// FAQ figures. The all-time recorded low (3,519.92 ft on 2023-04-13) is corroborated
// by NASA Earth Observatory ("just below 3,520 feet") and the American Southwest
// record cited via Glen Canyon NRA; it replaced an earlier 3,519.28 ft figure that no
// fetchable primary source substantiated (validated 2026-06-29). Exposed so the
// Powell page never types a reference number by hand. Other lakes render the band
// only if/when wired here.
export const POWELL_BAND = {
  fullPoolFt: 3700,
  minPowerPoolFt: 3490,
  deadPoolFt: 3370,
  recordLowFt: 3519.92,
  fullCapacityMaf: 27,
  lengthMi: 186,
};

// Net change across a reading's series (last minus first). The series spans ~30 days
// (SERIES_DAYS in fetch-levels.mjs), so this is the ~30-day elevation change. Pure
// math on the validated USGS reading; returns null if the series is too short.
export function changeOverSeries(series: { t: string; v: number }[] | undefined): number | null {
  if (!series || series.length < 2) return null;
  const last = series[series.length - 1].v;
  const first = series[0].v;
  if (!Number.isFinite(last) || !Number.isFinite(first)) return null;
  return Math.round((last - first) * 100) / 100;
}

// Linear share of the live-storage elevation band sitting below full pool. Honest
// geometric quantity (elevation distance), NOT a storage-volume claim — reservoirs
// are wider near the top so volume is not linear in elevation. Returns null unless
// both full pool and a lower band marker exist for the lake.
export function liveBandBelowFullPct(levelFt: number | null, fullPoolFt: number | null, lowerBandFt: number | null): number | null {
  if (levelFt == null || fullPoolFt == null || lowerBandFt == null) return null;
  const band = fullPoolFt - lowerBandFt;
  if (band <= 0) return null;
  return Math.round(((fullPoolFt - levelFt) / band) * 100 * 100) / 100;
}

