#!/bin/bash
# auto-update.sh — desktop data-refresh loop for lakelevelnow.com.
#
# Fully automated, NASA-grade: fetch fresh lake levels → build (gated) → commit
# → push. The push triggers .github/workflows/pages.yml on GitHub, which
# rebuilds lakelevelnow.com with fresh data. Run by launchd twice daily, and
# safe to run by hand.
#
# Guarantees:
#  • Single-flight — a lockdir prevents overlapping runs.
#  • Never pushes a broken build — `npm run build` must pass before any commit.
#  • Never force-push / never rewrites history — `git pull --ff-only` then plain
#    commit+push on main.
#  • Never deletes data on a flaky day — fetch-levels.mjs keeps last-known-good;
#    this script only commits what that produced.
#  • Idempotent — if nothing changed, no commit, no push.
#  • Loud logging — every run appends to ~/Library/Logs/lakelevelnow/update.log.

set -euo pipefail

# --- paths (launchd has a minimal PATH, so be explicit) -----------------------
export PATH="/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:$PATH"
PROJECT="/Users/mike/Desktop/portfolio-empire/lakelevelnow"
LOCK="$PROJECT/.auto-update.lock"
LOG_DIR="$HOME/Library/Logs/lakelevelnow"
LOG="$LOG_DIR/update.log"
mkdir -p "$LOG_DIR"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOG"; }

# --- single-flight (atomic mkdir lock; flock isn't on macOS) ------------------
if ! mkdir "$LOCK" 2>/dev/null; then
  # Stale lock guard: clear if older than 1h (a hung run).
  if [ -n "$(find "$LOCK" -mmin +60 2>/dev/null)" ]; then
    log "WARN: stale lock (>60m) — clearing"
    rmdir "$LOCK" 2>/dev/null || rm -rf "$LOCK"
  else
    log "SKIP: another run is active"
    exit 0
  fi
fi
trap 'rmdir "$LOCK" 2>/dev/null || true' EXIT

cd "$PROJECT"
log "=== run start ==="

# --- sync with remote (fast-forward only; never rewrite history) --------------
if ! git pull --ff-only --quiet >>"$LOG" 2>&1; then
  log "ERROR: git pull --ff-only failed (diverged?) — aborting to avoid clobbering"
  exit 1
fi

# --- fresh data ---------------------------------------------------------------
if ! npm run fetch >>"$LOG" 2>&1; then
  log "ERROR: fetch failed (circuit-breaker: zero fresh) — aborting, keeping prior data"
  exit 1
fi

# --- build gate: never push a site that doesn't build -------------------------
if ! npm run build >>"$LOG" 2>&1; then
  log "ERROR: build failed — NOT pushing (site stays on last good deploy)"
  exit 1
fi

# --- commit only the data the pipeline emits (never source churn by accident) --
git add -- src/data/lakes.json src/data/levels.json src/data/health.json 2>/dev/null || true
if git diff --cached --quiet; then
  log "no data change — nothing to push"
  log "=== run end (no-op) ==="
  exit 0
fi

# fresh-count line for an auditable commit message
FRESH=$(node -e "console.log(require('./src/data/health.json').fresh)" 2>/dev/null || echo "?")
TOTAL=$(node -e "console.log(require('./src/data/health.json').total)" 2>/dev/null || echo "?")
git commit -q -m "data: refresh lake levels ($FRESH/$TOTAL fresh) [auto]

Generated by scripts/auto-update.sh on the desktop.

Co-Authored-By: Claude <noreply@anthropic.com>"

# --- push (auth via gh keyring so it works headless under launchd) ------------
# Drop any invalid GITHUB_TOKEN from the calling env so gh reads the keyring.
# OAuth tokens (gho_) require username=x-access-token over HTTPS, NOT the
# account handle — using the handle caused "Invalid username or token".
# The leading `credential.helper=` RESETS the helper list so a stale token in
# the global `store` helper can't be tried (and rejected) before ours.
KT="$(env -u GITHUB_TOKEN -u GH_TOKEN gh auth token 2>/dev/null || true)"
if [ -n "$KT" ]; then
  git -c credential.helper= \
      -c "credential.helper=!f(){ echo username=x-access-token; echo \"password=$KT\"; };f" \
      push -u origin main >>"$LOG" 2>&1 \
    || { log "ERROR: git push failed (network) — data committed locally only"; exit 1; }
else
  git push -u origin main >>"$LOG" 2>&1 \
    || { log "ERROR: git push failed (no gh token / network) — data committed locally only"; exit 1; }
fi

log "pushed ($FRESH/$TOTAL fresh) → pages.yml will rebuild lakelevelnow.com"
log "=== run end (pushed) ==="
